#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $HELL_REPO == "hellbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $HELL_REPO == "HELLBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $HELL_REPO =~ $regex ]]
    then
        if [[ $HELL_REPO_BRANCH ]]
        then
            echo "${HELL_REPO}/archive/${HELL_REPO_BRANCH}.zip"
        else
            echo "${HELL_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_starter () {
    local zippath
    zippath="myhellbot.zip"
    echo "••• DOWNLOADING HELLBOT •••"
    wget -q $(_get_repolink) -O "$zippath"
    HELL_PATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    rm -rf "$zippath"
    sleep 5
    cd $HELL_PATH
    echo "••• STARTING HELLBOT •••"

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m hellbot
}

_starter
