#!/bin/bash


_hell_zip () {
    if [[ $GIT_REPO ]]
    then
        echo "https://github.com/${GIT_REPO}/archive/master.zip"
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMtVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}

_library () {
    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then 
        python3 -m PyrogramHell
    else
        python3 -m TelethonHell
    fi
}

_starter () {
    local hellpath
    hellpath="Plugins.zip"
    echo "••• DOWNLOADING HELLBOT •••"
    wget -q $(_hell_zip) -O "$hellpath"
    HELLPATH=$(zipinfo -1 "$hellpath" | grep -v "/.");
    unzip -qq "$hellpath"
    rm -rf "$hellpath"
    cd $HELLPATH
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING HELLBOT •••"
    _library
}

_starter
