#!/bin/bash


_hell_zip () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9iZXRhLnppcA==" | base64 -d
}

_starter () {
    local hellpath
    hellpath="Plugins.zip"
    echo "••• DOWNLOADING HELLBOT •••"
    wget -q $(_hell_zip) -O "$hellpath"
    HELLPATH=$(zipinfo -1 "$hellpath" | grep -v "/.");
    unzip -qq "$hellpath"
    rm -rf "$hellpath"
    cd $HELLPATH
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING HELLBOT •••"
    python3 -m hellbot
}

_starter
